# <center> Stinespring vs Krauss 
### <center> a comparison for the representation of open quantum system between
### <center> the stinespring dilation: $\mathcal{E}(\rho_A) = tr_E\left[ U_{AE} \left( \rho_A \otimes \ket{e_0}\bra{e_0} \right) U_{AE}^\dagger \right]$
### <center> and krauss representation: $\mathcal{E}(\rho_A) = \sum_k = E_k \rho_A E^\dagger_k$

## Amplitude Damping Channel

In [1]:
sys.path.append('..')
# reload local packages automatically
%load_ext autoreload
%autoreload 2

In [3]:
# import the necessary classes and methods from circuit and channel modules
from opentn.channels import get_krauss_from_unitary, quantum_channel, test_trace_preserving
from opentn.circuits import get_unitary_adchannel, quantum_circuit, get_unitary_beamsplitter
from opentn.states.qubits import plus, up, down
import numpy as np

# 1. $\ket{e_0} = \ket{0}$

In [38]:
# define global parameters
gamma = 0.5 # gamma parameters of amplitude damping channel
phys_init = plus # initial state of physical system
env_init = up # initial state of environment
# obtain U_AE from the circuit representation
U_AE = get_unitary_adchannel(gamma=gamma) 
# obtain U_AE from beam splitter
U_AE_BS = get_unitary_beamsplitter(gamma=gamma)

### From unitary of quantum circuit 

In [39]:
quantum_circuit(initial_state=[phys_init, env_init], U=U_AE)


(array([[0.75      +0.j, 0.35355339+0.j],
        [0.35355339+0.j, 0.25      +0.j]]),
 array([[0.75      +0.j, 0.35355339+0.j],
        [0.35355339+0.j, 0.25      +0.j]]))

### From general unitary of beamsplitter

In [40]:
quantum_circuit(initial_state=[phys_init, env_init], U=U_AE_BS)


(array([[0.75      +0.j, 0.35355339+0.j],
        [0.35355339+0.j, 0.25      +0.j]]),
 array([[0.75      +0.j, 0.35355339+0.j],
        [0.35355339+0.j, 0.25      +0.j]]))

### From known amplitude damping channel krauss operators

In [7]:
E0 = np.outer(up,up) + np.sqrt(1-gamma)*np.outer(down,down)
E1 = np.sqrt(gamma)*np.outer(up,down)
krauss_list = [E0, E1]

quantum_channel(state=phys_init, krauss_list=krauss_list)

array([[0.75      +0.j, 0.35355339+0.j],
       [0.35355339+0.j, 0.25      +0.j]])

### From krauss operators calculated using $U_{AE}$

In [10]:
krauss_list_from_unitary = get_krauss_from_unitary(U_AE)
quantum_channel(state=phys_init, krauss_list=krauss_list_from_unitary)

array([[0.75      +0.j, 0.35355339+0.j],
       [0.35355339+0.j, 0.25      +0.j]])

# 2. $\ket{e_0} = \ket{1}$

In [58]:
# define global parameters
gamma = 0.50 # gamma parameters of amplitude damping channel
phys_init = plus # initial state of physical system
env_init = down # initial state of environment
# obtain U_AE from the circuit representation
U_AE = get_unitary_adchannel(gamma=gamma) 
# obtain U_AE from beam splitter
U_AE_BS = get_unitary_beamsplitter(gamma=gamma)

### From unitary of quantum circuit 

In [59]:
quantum_circuit(initial_state=[phys_init, env_init], U=U_AE)

(array([[0.25      +0.j, 0.35355339+0.j],
        [0.35355339+0.j, 0.75      +0.j]]),
 array([[ 0.25      +0.j, -0.35355339+0.j],
        [-0.35355339+0.j,  0.75      +0.j]]))

In [60]:
print(U_AE)

[[ 1.        +0.j  0.        +0.j  0.        +0.j  0.        +0.j]
 [ 0.        +0.j  0.        +0.j  0.70710678+0.j  0.70710678+0.j]
 [ 0.        +0.j  0.        +0.j  0.70710678+0.j -0.70710678+0.j]
 [ 0.        +0.j  1.        +0.j  0.        +0.j  0.        +0.j]]


### From general unitary of beamsplitter

In [61]:
quantum_circuit(initial_state=[phys_init, env_init], U=U_AE_BS)

(array([[0.25      +0.j, 0.35355339+0.j],
        [0.35355339+0.j, 0.75      +0.j]]),
 array([[ 0.25      +0.j, -0.35355339+0.j],
        [-0.35355339+0.j,  0.75      +0.j]]))

In [62]:
print(U_AE_BS)

[[ 1.        +0.j  0.        +0.j  0.        +0.j  0.        +0.j]
 [ 0.        +0.j  0.70710678+0.j  0.70710678+0.j  0.        +0.j]
 [ 0.        +0.j -0.70710678+0.j  0.70710678+0.j  0.        +0.j]
 [ 0.        +0.j  0.        +0.j  0.        +0.j  1.        +0.j]]


### From krauss operators calculated using $U_{AE}$

In [63]:
krauss_list_one_circuit = get_krauss_from_unitary(U_AE, env_init=env_init)
krauss_list_one_circuit

[array([[ 0.        +0.j,  0.        +0.j],
        [ 0.        +0.j, -0.70710678+0.j]]),
 array([[0.        +0.j, 0.70710678+0.j],
        [1.        +0.j, 0.        +0.j]])]

In [64]:
test_trace_preserving(krauss_list_one_circuit)

Trace Preserving


array([[1.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j]])

In [65]:
krauss_list_one_bs = get_krauss_from_unitary(U_AE_BS, env_init=env_init)
krauss_list_one_bs

[array([[ 0.        +0.j,  0.        +0.j],
        [-0.70710678+0.j,  0.        +0.j]]),
 array([[0.70710678+0.j, 0.        +0.j],
        [0.        +0.j, 1.        +0.j]])]

In [66]:
test_trace_preserving(krauss_list_one_bs)

Trace Preserving


array([[1.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j]])

In [67]:
quantum_channel(state=phys_init, krauss_list=krauss_list_one_bs)

array([[0.25      +0.j, 0.35355339+0.j],
       [0.35355339+0.j, 0.75      +0.j]])

In [68]:
quantum_channel(state=phys_init, krauss_list=krauss_list_one_circuit)

array([[0.25      +0.j, 0.35355339+0.j],
       [0.35355339+0.j, 0.75      +0.j]])

# My conclusions:
- we can see how changing the environment system from $\ket{0} \rightarrow \ket{1}$, also changes the final density matrix.
    > I think this is due to the fact that starting in $\ket{+1}$ makes us end up in a state that has $\ket{02}$ and $\ket{20}$, which means we would need to take into account higher energy states not only on circuit, but also in kets. Also would need a third krauss operator
- unitary from amplitude damping channel circuit and beam splitter differ (and therefore produce different krauss operators), yet they yield the same output density matrix
    > this is as expected as $U_AE$ and $E_k$ are only unique up to unitary transformations